language: java
jdk:
    - oraclejdk8
    - oraclejdk7
env:
    - TEST_DIR=spi/jlibrpi-spi
    - TEST_DIR=spi/jlibrpi-spi-iqrf
    - TEST_DIR=spi/jlibrpi-spi-iqrf-examples
    - TEST_DIR=io/jlibrpi-io
    - TEST_DIR=io/jlibrpi-io-examples
script:
    - cd $TEST_DIR
    - mvn test
